version: '3.8'

services:
  backend:
    build:
      context: .  
      dockerfile: BlogAppAec.Api/Dockerfile.backend  
    ports:
      - "5154:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  frontend:
    build:
      context: ./BlogAppAec.Api/ClientApp   
      dockerfile: Dockerfile.frontend     
    ports:
      - "4200:80"  


